version: '3'

services:
  # Backend configuration
  backend:
    build:
      context: ./server
    ports:
      - "5001:5000"
    depends_on:
      - database
    environment:
      - MONGO_URI=mongodb://mongo:27017/cinetrunkdb
      - JWT_SECRET=
    networks:
      - cinetrunk_network

  database:
    # Database configuration
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - cinetrunk_network
  
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - cinetrunk_network

volumes:
  mongo_data:

networks:
  cinetrunk_network:
