services:
  # Backend configuration
  backend:
    build:
      context: ./server
    ports:
      - "5001:5000"
    depends_on:
      - database
    environment:
      - MONGODB_URI=mongodb+srv://alu0101463018:UTKdPf3do7rqsU0s@cinetrunk.r9nmg.mongodb.net/?retryWrites=true&w=majority&appName=CineTrunk
    networks:
      - cinetrunk_network

  database:
    # Database configuration
    image: mongo:5
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - cinetrunk_network
  
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "8080:8080"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - cinetrunk_network

volumes:
  mongodb_data:

networks:
  cinetrunk_network:
