name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  backend:
    name: Backend Tests and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: ./backend
        run: npm install

      - name: Setup Environment Variables
        run: echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> $GITHUB_ENV
             echo "TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}" >> $GITHUB_ENV

      - name: Run Tests
        working-directory: ./backend
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: npm test

      - name: Build Backend
        working-directory: ./backend
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: npm run build

  frontend:
    name: Frontend Tests and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run Tests
        working-directory: ./frontend
        run: npm test

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build